# Generated by Django 4.0.3 on 2022-04-02 13:55

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('imagem', stdimage.models.StdImageField(upload_to='tarefas')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_prevista', models.DateTimeField()),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('concluida', models.BooleanField(default=False)),
                ('prioridade', models.IntegerField(default=0)),
            ],
        ),
    ]
