# Generated by Django 4.0.3 on 2022-04-03 15:28

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='descricao',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='imagem',
            field=stdimage.models.StdImageField(null=True, upload_to='tarefas'),
        ),
    ]
